[build]
  base = "oraculum-novo-main/oraculum-novo-main"
  command = "npm run build"
  publish = "oraculum-novo-main/oraculum-novo-main/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
